### PR TITLE
specify mysite.books.models instead of just books.models

### PR DESCRIPTION
**Pull request by nicboul**

### CODE REVIEW

**Comment by lfolco** [comment]
hi-

when i've been going through it, using mysite.books.models resulted in an error. my directory structure is as follows. i followed the instructions pretty clearly. i'm using version django version 1.4

```
mysite
    - books
       - __init__.py
       - admin.py
       - models.py
       - tests.py
       - views.py
    - mysite
       - __init__.py
       - settings.py
       - urls.py
       - views.py
       - wsgi.py
    - templates
       - books
           - search_form.html
           - search_results.html
       - base.html
       - current_datetime.html
       - display_meta.html
       - hours_ahead.html
    - manage.py
```

is that how you have your directory setup? i'm not sure if i'm doing this wrong :)

**Comment by alvinkatojr** [comment]
Hello Laura:
Thanks for your query. Please post the error you are getting so that we can
get debug it.

Also your directory structures seems cluttered,
mysite
mysite
- _init_.py
- settings.py
- urls.py
- wsgi.py
- templates
  books
  - _init_.py
  - admin.py
  - models.py
  - tests.py
  - views.py
    templates
  - search_form.html
  - search_results.html
  - base.html
  - current_datetime.html
  - display_meta.html
  - hours_ahead.html
    manage.py

'mysite.books.models' is referencing a directory structure with mysite at
the top tier(representing the project), books second line(the books app)
and the models file next. It could be that the model file is inaccessible
give the structure you have, so I advise you restructure your files to
match what I have showed you up here.

Hope that clears you up, let me know how it goes.

Al

**Comment by alvinkatojr** [comment]
Sorry here is a better arrangement.  Check if your structure aligns.

mysite
mysite
- _init_.py
- settings.py
- urls.py
- wsgi.py
- templates
  books
  - _init_.py
  - admin.py
  - models.py
  - tests.py
  - views.py
    templates
  - search_form.html
  - search_results.html
  - base.html
  - current_datetime.html
  - display_meta.html
  - hours_ahead.html
    manage.py

**Comment by jacobian** [comment]
It should just be `books.models`. It's possible there's other things wrong that lead to that not working, but those should be fixed, not this.

**Pull request closed without merging**
